import SnackbarContext from "@/utils/snackbarContext";
import theme from "@/utils/theme";
import { ThemeProvider } from "@mui/material";
import { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import Sidebar from "@/components/Shared/Sidebar";
import { Header } from "@/components/Shared/Header";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SnackbarContext>
          <ThemeProvider theme={theme}>
            <div className="flex">
              <Sidebar />
              <div className="w-full flex flex-col">
                <Header />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </SnackbarContext>
      </body>
    </html>
  );
}
